/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_elouyi_lely_LelyNative */

#ifndef _Included_com_elouyi_lely_LelyNative
#define _Included_com_elouyi_lely_LelyNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_elouyi_lely_LelyNative
 * Method:    lolDir
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_elouyi_lely_LelyNative_lolDir
  (JNIEnv *env, jclass);

JNIEXPORT jbyteArray JNICALL Java_com_elouyi_lely_LelyNative_lolDirBytes
  (JNIEnv *env, jclass);

#ifdef __cplusplus
}
#endif
#endif
